export const SET_USER = 'SET_USER'
export const SET_TIMELINE = 'SET_TIMELINE'
export const SET_SELECTED_PROFILE = 'SET_SELECTED_PROFILE'
export const SET_FRIENDSHIPS = 'SET_FRIENDSHIPS'

export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_REACTION = 'ADD_REACTION'

export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION'
export const SET_NEARBY = 'SET_NEARBY'
